services:
  server:
    build: .
    ports:
      - "5000"
    volumes:
      - ./uploads:/app/uploads
  client:
    build: gui/
    ports:
      - "3000"
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
